export default {
    ADD_FAVORITE_PLAYER: 'ADD_FAVORITE_PLAYER',
    REMOVE_FAVORITE_PLAYER: 'REMOVE_FAVORITE_PLAYER',
    ADD_FAVORITE_TEAM: 'ADD_FAVORITE_TEAM',
    REMOVE_FAVORITE_TEAM: 'REMOVE_FAVORITE_TEAM',
    SET_USER_LOGGED: 'SET_USER_LOGGED',
    SET_USER_EMAIL: 'SET_USER_EMAIL',
    SET_PLAYER_DATA: 'SET_PLAYER_DATA',
    SORT_FAVORITE_PLAYERS: 'SORT_FAVORITE_PLAYERS',
    FILTER_FAVORITE_PLAYERS_BY_GOALS: 'FILTER_FAVORITE_PLAYERS_BY_GOALS',
    FILTER_FAVORITE_PLAYERS_BY_RED_CARDS: 'FILTER_FAVORITE_PLAYERS_BY_RED_CARDS',
    SET_COUNTRIES: 'SET_COUNTRIES',
}