export default {
    ADD_FAVORITE_PLAYER: 'ADD_FAVORITE_PLAYER',
    REMOVE_FAVORITE_PLAYER: 'REMOVE_FAVORITE_PLAYER',
    ADD_FAVORITE_TEAM: 'ADD_FAVORITE_TEAM',
    REMOVE_FAVORITE_TEAM: 'REMOVE_FAVORITE_TEAM'
}